#!/bin/sh

if [ $# -gt 0 ] && [ $1 = '--' ]; then
        shift # the first argument is '--'
fi
if [ $# -lt 1 ]; then
        echo "Usage: $0 <grep pattern>"
        exit 127
fi

for line in $(p4 files //mw/Bcgir_core/.../*$1* |
        cut -d' ' -f1 |
        cut -d'#' -f1);
do p4 where $line |
        cut -d' ' -f3;
done
